import { Button, CircularProgress } from "@material-ui/core";
import Head from "next/head";
import React, { useState } from "react";
import styles from "../styles/Home.module.css";

const HomePage: React.FC = () => {
  const [loading, setLoading] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Button
        variant="contained"
        color="primary"
        startIcon={loading && <CircularProgress size={21} color="secondary" />}
      >
        IPFS
      </Button>
    </div>
  );
};

export default HomePage;
